<?php

namespace EMM\UsertwoBundle\Entity;

/**
 * UsertwoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsertwoRepository extends \Doctrine\ORM\EntityRepository
{
}
